name: Go

on:
  push:
    branches: [ "aws" ]
  pull_request:
    branches: [ "aws" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build & Zip
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip main.zip main

    - name: Deploy
      uses: appleboy/lambda-action@v0.1.5
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: GambunBot
        zip_file: main.zip
        handler: main
        role: ${{ secrets.AWS_SERVICE_ROLE_ID }}
        runtime: go1.x
